image: docker.io/gumjoe/wacc-ci-scala:slim

stages:
  - parser
  - analyser
  - generator

parser:
  stage: parser
  script:
    - scala-cli test . --test-only src.test.Parser

analyser:
  stage: analyser
  script:
    - scala-cli test . --test-only src.test.Analyser

generator:
  stage: generator
  script:
    - scala-cli test . --test-only src.test.Generator
